# Importing Necessary Modules


In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import numpy as np

# IRIS dataset

In [2]:
df=pd.read_csv("IRIS.csv")

# Data Cleaning

In [3]:
df=df['5.1|3.5|1.4|0.2|Iris-setosa'].str.split("|",expand=True)

In [4]:
df=df.iloc[1:]

In [5]:
df.rename(columns={0:"Petal Lenght",1:"Petal Width",2:"Sepal Length",3:"Sepal Width"},inplace=True)

In [6]:
df.rename(columns={4:"Class"},inplace=True)

In [7]:
df.reset_index(inplace=True)

In [8]:
df.drop(columns=["index"],inplace=True)

In [9]:
df.dropna(inplace=True)

In [10]:
df.isnull().sum()

Petal Lenght    0
Petal Width     0
Sepal Length    0
Sepal Width     0
Class           0
dtype: int64

In [11]:
df.shape

(152, 5)

# Scaling the data and Test,Train split


In [12]:
scaler=MinMaxScaler()

In [13]:
X=df.drop(columns=["Class"])

In [14]:
X.replace("",0,inplace=True)

In [15]:
X=scaler.fit_transform(X)

In [16]:
y=df.drop(columns=["Petal Lenght","Petal Width","Sepal Length","Sepal Width"])

In [17]:
df.drop(columns=["Petal Lenght","Petal Width","Sepal Length","Sepal Width"])

Class
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
148  Iris-virginica
149  Iris-virginica
150  Iris-virginica
151  Iris-virginica
152  Iris-virginica

[152 rows x 1 columns]

In [19]:
labe_encoder=LabelEncoder()

In [21]:
y=labe_encoder.fit_transform(y)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [22]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [23]:
y[y==0]=1

In [24]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4)

# Creating the Random Forest Model


In [26]:
rf_classifier = RandomForestClassifier(n_estimators=100)


In [27]:
rf_classifier.fit(X_train, y_train)

RandomForestClassifier()

In [28]:
y_pred = rf_classifier.predict(X_test)

In [29]:
X_test[0]

array([0.74683544, 0.68181818, 0.73913043, 0.72      ])

In [30]:
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

# Accuracy: 96.72131147540983
Classification Report:
               precision    recall  f1-score   support

           1       1.00      1.00      1.00        16
           2       0.92      1.00      0.96        24
           3       1.00      0.90      0.95        21

    accuracy                           0.97        61
   macro avg       0.97      0.97      0.97        61
weighted avg       0.97      0.97      0.97        61


In [32]:
input_data=(4.6,3.1,1.5,0.2)

In [33]:
input_arr=np.asarray(input_data)

In [34]:
input_arr=input_arr.reshape(1,-1)

In [35]:
pred=rf_classifier.predict(input_arr)

In [36]:
pred[0]

1

In [37]:
## 1 set 2 vir 3 versi