# Importing Necessary Modules


In [450]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import numpy as np

# IRIS dataset

In [451]:
df=pd.read_csv("IRIS.csv")

# Data Cleaning

In [452]:
df=df['5.1|3.5|1.4|0.2|Iris-setosa'].str.split("|",expand=True)

In [453]:
df=df.iloc[1:]

In [454]:
df.rename(columns={0:"Petal Lenght",1:"Petal Width",2:"Sepal Length",3:"Sepal Width"},inplace=True)

In [455]:
df.rename(columns={4:"Class"},inplace=True)

In [456]:
df.reset_index(inplace=True)

In [457]:
df.drop(columns=["index"],inplace=True)

In [458]:
df.dropna(inplace=True)

In [459]:
df.isnull().sum()

Petal Lenght    0
Petal Width     0
Sepal Length    0
Sepal Width     0
Class           0
dtype: int64

In [460]:
df.shape

(152, 5)

# Scaling the data and Test,Train split


In [461]:
scaler=MinMaxScaler()

In [462]:
X=df.drop(columns=["Class"])

In [463]:
X.replace("",0,inplace=True)

In [464]:
X=scaler.fit_transform(X)

In [495]:
y.head

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [465]:
y=df.drop(columns=["Petal Lenght","Petal Width","Sepal Length","Sepal Width"])

In [466]:
df.drop(columns=["Petal Lenght","Petal Width","Sepal Length","Sepal Width"])

Class
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
148  Iris-virginica
149  Iris-virginica
150  Iris-virginica
151  Iris-virginica
152  Iris-virginica

[152 rows x 1 columns]

In [467]:
y=label_encoder.fit_transform(y)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [468]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [469]:
y[y==0]=1

In [484]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [471]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4)

# Creating the Random Forest Model


In [472]:
rf_classifier = RandomForestClassifier(n_estimators=100)


In [473]:
rf_classifier.fit(X_train, y_train)

RandomForestClassifier()

In [474]:
y_pred = rf_classifier.predict(X_test)

In [475]:
X_test[0]

array([0.70886076, 0.65909091, 0.52173913, 0.52      ])

In [476]:
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

In [477]:
print("Accuracy:", accuracy*100)
print("Classification Report:\n", report)


Accuracy: 95.08196721311475
Classification Report:
               precision    recall  f1-score   support

           1       1.00      1.00      1.00        16
           2       0.96      0.92      0.94        24
           3       0.91      0.95      0.93        21

    accuracy                           0.95        61
   macro avg       0.96      0.96      0.96        61
weighted avg       0.95      0.95      0.95        61



In [517]:
input_data=(4.6,3.1,1.5,0.2)

In [518]:
input_arr=np.asarray(input_data)

In [519]:
input_arr=input_arr.reshape(1,-1)

In [520]:
pred=rf_classifier.predict(input_arr)

In [521]:
pred[0]

1

In [514]:
## 1 set 2 vir 3 versi

In [515]:
df.drop(columns=["Class"]).head(100)

Petal Lenght Petal Width Sepal Length Sepal Width
0            4.9         3.0          1.4         0.2
1            4.7         3.2          1.3         0.2
2            4.6         3.1          1.5         0.2
3            5.0         3.6          1.4         0.2
4            5.4         3.9          1.7         0.4
..           ...         ...          ...         ...
96           5.0         2.3          3.3         1.0
97           5.6         2.7          4.2         1.3
98           5.7         3.0          4.2         1.2
99           5.7         2.9          4.2         1.3
100          6.2         2.9          4.3         1.3

[100 rows x 4 columns]

In [516]:
df.drop(columns=["Petal Lenght","Petal Width","Sepal Length","Sepal Width"]).head(100)

Class
0        Iris-setosa
1        Iris-setosa
2        Iris-setosa
3        Iris-setosa
4        Iris-setosa
..               ...
96   Iris-versicolor
97   Iris-versicolor
98   Iris-versicolor
99   Iris-versicolor
100  Iris-versicolor

[100 rows x 1 columns]